version: 2	
requirements:
  signed_off_by:
    required: false
group_defaults:	
  approve_by_comment:	
    approve_regex: '^(Approved|:shipit:|:\+1:|LGTM)'	
      enabled: true	
groups:	
  approved-editors:	
    github_reviews:	
      enabled: true	
    required: 1	
    reset_on_push:	
      enabled: false	
    teams:	
      - approved-editors 