title: MineColonies Wiki
description: >- # this means to ignore newlines until "remote-theme"
  Welcome to the MineColonies Wiki!
remote-theme: jekyll/minima
markdown: kramdown
baseurl: /
plugins:
- jekyll-seo-tag
