project_identifier: minecolonies-wiki
base_path: .
files:
  - source: source/**/*.md
    translation: /%two_letters_code%/**/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-br
